### ISSUE TITLE
BSOD (MANUALLY_INITIATED_CRASH) on 1803 / ver. 17134

### ISSUE THREAD

**Issue by ghost** [tandasat/GuardMon#4]
Hey,
I wanted to try out your debugging-framework, but sadly I always get a BSOD.
Here is an MEMORY.DMP out from my system:

The logfile from GuardMon says:
`00:20:26.253	INF	#3	    4	 6244	System         	Log has been initialized.
00:20:26.271	INF	#0	    4	 6244	System         	Initializing VMX for the processor 0.
00:20:26.346	INF	#0	    4	 6244	System         	Initialized successfully.
00:20:26.347	INF	#1	    4	 6244	System         	Initializing VMX for the processor 1.`
After that the BSOD with „MANUALLY_INITIATED_CRASH„  get hit.

**Comment by tandasat** [comment]
Please pull the latest commits (both in GuardMon and submodule, HyperPlatform). This should be fixed now with commit 3adfd28

**Comment by ghost** [comment]
> 
> 
> Please pull the latest commits (both in GuardMon and submodule, HyperPlatform). This should be fixed now with commit [3adfd28](https://github.com/tandasat/GuardMon/commit/3adfd28de8f3b6812a5a28b93835b7418d3ff182)

Thanks, working as intended now!
