### ISSUE TITLE
Disable certain features of GuardMon

### ISSUE THREAD

**Issue by ghost** [tandasat/GuardMon#6]
Hey, 
How could I disable these features of GuardMon?
monitoring system register accesses. GuardMon is capable of logging read and write activities on CR0, CR4, debug registers, GDT, IDT and MSRs from kernel memory not backed by any images.
I don’t really need it anymore, I’m just interested into the patchguard disarming option.

**Comment by ghost** [comment]
I ask this because if have some sort of delay If i use my own kernel driver. Like I create a driver and communicate with a usermode app, but somehow when I loaded GuardMon I have a delay while communicating. Do you have an idea what could be the issue? My own kernel driver is just ring 0 no hypervisor.

**Comment by tandasat** [comment]
What you should change to remove them can be found in the diff in HyperPlatform and an added file for GuardMon specifically. 
https://github.com/tandasat/HyperPlatform/compare/guardmon

It should be noted that PatchGuard disarming will not work on Windows 10+, and you want to research and implement that yourself.

**Comment by radoradovan** [comment]
It worked fine. 
I only have the issue that when I loaded GuardMon, communicating with my own driver is delayed. I have no idea why

**Comment by ghost** [comment]
I use KeReadVirtualMemory/KeWriteVirtualMemory in my driver, but somehow after loading up GuardMon there is a huge delay when trying to read/write of a proc.
